adres = [("Swiateczna",
              "234",
              5,
              "Warszawa",
              "02-326"),
             ("Choinkowa",
              "34A",
              1,
              "Krakow",
              "31-326"
              ),
             ("Mikolaja Swietego",
              "87",
              3,
              "Rzeszow",
              "40-326"
              ),
             ("Bombkowa",
              "214",
              55,
              "Gdansk",
              "15-326"
              ),
             ("Prezentowa",
              "543",
              765,
              "Warszawa",
              "02-326"
              ),
             ("Serniczkowa",
              "4B",
              2,
              "Krakow",
              "02-326"
              ),
             ("Pierniczkowa",
              "289",
              55,
              "Gdansk",
              "02-326"
              ),
             ("Barszczykowa",
              "234",
              5,
              "Rzeszow",
              "37-326"
              ),
             ("Uszkowa",
              "43H",
              5,
              "Wroclaw",
              "02-326"
              ),
             ("Cukierkowa",
              "23",
              5,
              "Poznan",
              "02-326"
              )]

b = sorted(sorted(adres, key = lambda x : x[0]))
print(b)
